# Generated by Django 4.1.7 on 2023-03-09 07:07

from django.db import migrations, models
import django.db.models.deletion
import first_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green')], max_length=255)),
                ('image', models.ImageField(upload_to=first_app.models.get_image_filename)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc', models.CharField(max_length=25, verbose_name='NC')),
                ('pc', models.CharField(max_length=25, verbose_name='PC')),
                ('nt', models.CharField(max_length=25, verbose_name='NT')),
                ('t', models.CharField(max_length=25, verbose_name='T')),
                ('ng', models.CharField(max_length=25, verbose_name='NG')),
                ('related_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.datamodel')),
            ],
        ),
    ]
