# Generated by Django 4.1.7 on 2023-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_datamodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
